division: Ligue 1
relevant_columns:
  Date: match_date
  HomeTeam: home_team
  AwayTeam: away_team
  FTR: winner
  FTHG: home_goals
  FTAG: away_goals
  HS: home_shots
  AS: away_shots
  HST: home_shots_on_target
  AST: away_shots_on_target
  HC: home_corners
  AC: away_corners
  HY: home_yellow_cards
  AY: away_yellow_cards
  HR: home_red_cards
  AR: away_red_cards
final_schema:
  - division
  - match_date
  - home_team
  - away_team
  - winner
  - home_goals
  - away_goals
  - home_shots
  - away_shots
  - home_shots_on_target
  - away_shots_on_target
  - home_corners
  - away_corners
  - home_yellow_cards
  - away_yellow_cards
  - home_red_cards
  - away_red_cards
  - normalization_datetime
  - normalization_uuid
